### ISSUE TITLE
How to test stdout / stderr?

### ISSUE THREAD

**Issue by hrj** [sn127/utils#16]
Is there an easy way to test stdout / stderr?

**Comment by jaa127** [comment]
There might be an (easy) way to test stdout and stderr.

The hard part is to get actual stdout and/or stderr to the file, DirSuite doesn't do that automatically.

What you can do (if it's not an option to direct those warning messages to the log file):

1) Define few extra arguments based on testname:
https://github.com/hrj/abandon/blob/master/cli/src/test/scala/co/uproot/abandon/DefaultArgsDirSuite.scala#L20
In that function you have nicely testname available, which is already to used generage `testname.conf` Based on testname, inject output file names for stdout /stderr redirect to the `args`:
Names should be for example:
    - `out.testname.stdout.txt`
    - `out.testname.stderr.txt`
 
2) Make special runDirSuiteTestCases group, where you surround `mainStatus` with stdout and stderr redirect code.  At that point you will have correct file names in `args`:
 https://github.com/hrj/abandon/blob/master/cli/src/test/scala/co/uproot/abandon/CliTest.scala#L20
 for actual `mainStatus` call,  strip or truncate those extra args away from `args`. 

3) After `mainStatus`  returns, restore redirect, because otherwise funny things will happen.

4) Define normal references for Dirsuite, e.g.
     - `testname.ref.stdout.txt`
     - `testname.ref.stderr.txt`

Now if outputs are same, test should pass.
